[project]
name = "auto-shutdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.58",
    "pillow>=12.1.1",
    "pyinstaller>=6.19.0",
    "requests>=2.32.5",
]
